-- ============================================================
-- AI Front-Desk Twin — Phase 1
--
-- Persisted ledger for every AI-generated reply suggestion. Drafts
-- were ephemeral before this — generated by /api/leads/[id]/draft-
-- message, returned to the client, never stored. To measure what
-- humans accept, edit, and reject (the signal Phase 2 autonomy will
-- be built on), we have to persist them.
--
-- One row per draft. A draft is born 'pending' (auto-generated on
-- inbound). It transitions to:
--   'sent'              — human pressed Send unchanged
--   'edited'            — human modified body, then sent
--   'rejected'          — human typed their own reply or chose
--                         silence; the draft was discarded
--   'expired'           — older than 24h with no resolution (cron
--                         sweep handles this in a later commit)
--   'guardrail_failed'  — failed the safety post-validation pass
--                         (never shown to the user)
--
-- Org-scoped via RLS. Same isolation pattern as `messages`.
-- ============================================================

create table public.ai_drafts (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null
    references public.organizations(id) on delete cascade,
  contact_id uuid not null
    references public.contacts(id) on delete cascade,

  -- 'sms' today; 'email' in Phase 2.
  channel text not null check (channel in ('sms', 'email')),

  -- The inbound message that triggered this draft. Optional for
  -- manually-invoked drafts (the existing AI Draft button), which
  -- have no inbound trigger.
  trigger_message_id uuid
    references public.messages(id) on delete set null,

  -- The draft text the model produced (post-guardrails if pass).
  draft_body text not null,
  -- Email subject — null for SMS drafts.
  draft_subject text,

  -- Model name (e.g. 'claude-haiku-4-5'). Lets us A/B model
  -- versions and detect drift over time.
  model text not null,

  -- JSON snapshot of what was fed to the model: last N messages,
  -- contact procedure interest, source, etc. Storing the snapshot
  -- lets us replay drafts and analyze why one generation was good
  -- and another wasn't, without re-fetching the same context.
  context_snapshot jsonb,

  -- Lifecycle.
  state text not null default 'pending'
    check (state in ('pending', 'sent', 'edited', 'rejected', 'expired', 'guardrail_failed')),

  -- Levenshtein distance between draft_body and the body the human
  -- actually sent. 0 = sent unchanged. NULL until resolution.
  edit_distance integer,

  -- The messages.id of the outbound row created when this draft was
  -- sent. Null for rejected/expired/guardrail_failed.
  sent_message_id uuid
    references public.messages(id) on delete set null,

  -- Why the draft was rejected, if applicable. Free-text — populated
  -- by the user's choice when we add a "tell us why" prompt in
  -- Phase 1.5.
  rejection_reason text,

  -- Which guardrail rule killed it. Null when state != 'guardrail_failed'.
  guardrail_violation text,

  generated_at timestamptz not null default now(),
  resolved_at  timestamptz
);

-- ────────────────────────────────────────────────────────────
-- Indexes
-- ────────────────────────────────────────────────────────────

-- The hot read path: "give me the pending draft for this contact."
-- The conversation pane will hit this every time the user opens a
-- thread, so it has to be fast.
create index ai_drafts_contact_pending_idx
  on public.ai_drafts (contact_id, generated_at desc)
  where state = 'pending';

-- Analytics path: "all drafts for this org in the last 30 days,
-- group by state." Powers the weekly metrics tile.
create index ai_drafts_org_generated_idx
  on public.ai_drafts (organization_id, generated_at desc);

-- One pending draft per (contact, trigger). Prevents duplicate
-- drafts when the inbound webhook retries — Twilio retries on
-- non-2xx and the auto-draft hook runs after the messages insert.
create unique index ai_drafts_one_pending_per_trigger_idx
  on public.ai_drafts (trigger_message_id)
  where state = 'pending' and trigger_message_id is not null;

-- ────────────────────────────────────────────────────────────
-- RLS — org isolation, same shape as messages/contacts
-- ────────────────────────────────────────────────────────────

alter table public.ai_drafts enable row level security;

create policy ai_drafts_org_isolation on public.ai_drafts
  for all
  using (
    organization_id in (
      select organization_id from public.profiles where id = auth.uid()
    )
  )
  with check (
    organization_id in (
      select organization_id from public.profiles where id = auth.uid()
    )
  );

grant select, insert, update, delete on public.ai_drafts
  to authenticated, service_role;
